import { Workspace, Goal, Milestone, Task, UserProfile, ActivityEvent, Notification, WorkspaceMember } from "@/types/planforge";

export const SEED_USERS: UserProfile[] = [
  {
    id: "u-sushanth",
    email: "sushanth@planforge.dev",
    full_name: "Sushanth",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "u-rahul",
    email: "rahul@planforge.dev",
    full_name: "Rahul Verma",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: "u-neha",
    email: "neha@planforge.dev",
    full_name: "Neha Sharma",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "u-priya",
    email: "priya@planforge.dev",
    full_name: "Priya Patel",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=128&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  }
];

export const CURRENT_USER: UserProfile = SEED_USERS[0];

const now = new Date();
const d = (daysOffset: number) => {
  const target = new Date(now.getTime() + daysOffset * 86400000);
  return target.toISOString();
};

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: "ws-ai-hackathon",
    name: "AI Hackathon: Resume Analyzer",
    description: "48-hour build for the National AI Challenge. Building an automated resume intelligence & JD matcher.",
    type: "hackathon",
    deadline: d(3),
    created_by: "u-sushanth",
    created_at: d(-2),
    updated_at: d(0),
  },
  {
    id: "ws-ml-journey",
    name: "Machine Learning Foundations",
    description: "Personal and team mastery roadmap covering Python, Linear Algebra, PyTorch, and Deep Learning.",
    type: "learning",
    deadline: d(45),
    created_by: "u-sushanth",
    created_at: d(-10),
    updated_at: d(-1),
  },
  {
    id: "ws-campus-portal",
    name: "Campus Connect Portal",
    description: "Final Year Capstone Project: Unified student resource sharing, attendance and event tracking platform.",
    type: "project",
    deadline: d(14),
    created_by: "u-rahul",
    created_at: d(-15),
    updated_at: d(0),
  }
];

export const INITIAL_MEMBERS: WorkspaceMember[] = [
  { id: "wm-1", workspace_id: "ws-ai-hackathon", user_id: "u-sushanth", role: "owner", joined_at: d(-2), profile: SEED_USERS[0] },
  { id: "wm-2", workspace_id: "ws-ai-hackathon", user_id: "u-rahul", role: "admin", joined_at: d(-2), profile: SEED_USERS[1] },
  { id: "wm-3", workspace_id: "ws-ai-hackathon", user_id: "u-neha", role: "member", joined_at: d(-1), profile: SEED_USERS[2] },
  { id: "wm-4", workspace_id: "ws-ai-hackathon", user_id: "u-priya", role: "member", joined_at: d(-1), profile: SEED_USERS[3] },

  { id: "wm-5", workspace_id: "ws-ml-journey", user_id: "u-sushanth", role: "owner", joined_at: d(-10), profile: SEED_USERS[0] },
  { id: "wm-6", workspace_id: "ws-ml-journey", user_id: "u-neha", role: "member", joined_at: d(-8), profile: SEED_USERS[2] },

  { id: "wm-7", workspace_id: "ws-campus-portal", user_id: "u-rahul", role: "owner", joined_at: d(-15), profile: SEED_USERS[1] },
  { id: "wm-8", workspace_id: "ws-campus-portal", user_id: "u-sushanth", role: "member", joined_at: d(-14), profile: SEED_USERS[0] },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: "goal-resume-core",
    workspace_id: "ws-ai-hackathon",
    title: "Build AI Resume Analyzer Engine",
    description: "End-to-end extraction, vector embedding matching, and scoring pipeline against Job Descriptions.",
    status: "in_progress",
    priority: "urgent",
    target_date: d(2),
    created_by: "u-sushanth",
    created_at: d(-2),
    updated_at: d(0),
  },
  {
    id: "goal-resume-ui",
    workspace_id: "ws-ai-hackathon",
    title: "Sleek Candidate & Recruiter Dashboard",
    description: "Responsive Next.js interface with real-time analysis reports, match radar charts, and PDF viewer.",
    status: "in_progress",
    priority: "high",
    target_date: d(3),
    created_by: "u-rahul",
    created_at: d(-2),
    updated_at: d(0),
  },
  {
    id: "goal-ml-math",
    workspace_id: "ws-ml-journey",
    title: "Mathematics & Vector Calculus Core",
    description: "Cover gradient descent mechanics, matrix factorization, and loss function derivations.",
    status: "completed",
    priority: "high",
    target_date: d(-2),
    created_by: "u-sushanth",
    created_at: d(-10),
    updated_at: d(-2),
  },
  {
    id: "goal-ml-deep",
    workspace_id: "ws-ml-journey",
    title: "Deep Learning & Transformer Architectures",
    description: "Hands-on PyTorch implementations of Attention mechanisms and vision transformers.",
    status: "in_progress",
    priority: "medium",
    target_date: d(30),
    created_by: "u-sushanth",
    created_at: d(-5),
    updated_at: d(0),
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: "ms-1",
    goal_id: "goal-resume-core",
    workspace_id: "ws-ai-hackathon",
    title: "1. Problem & Architecture Spec",
    description: "Finalize schema, embeddings model choice, and API contracts.",
    due_date: d(-1),
    status: "completed",
    order_index: 0,
    created_at: d(-2),
    updated_at: d(-1),
  },
  {
    id: "ms-2",
    goal_id: "goal-resume-core",
    workspace_id: "ws-ai-hackathon",
    title: "2. PDF Parser & AI Pipeline",
    description: "Build robust PDF extraction, chunking, and embedding generation.",
    due_date: d(1),
    status: "in_progress",
    order_index: 1,
    created_at: d(-2),
    updated_at: d(0),
  },
  {
    id: "ms-3",
    goal_id: "goal-resume-core",
    workspace_id: "ws-ai-hackathon",
    title: "3. Vector Matching & Scoring API",
    description: "Implement semantic similarity and missing skills scoring engine.",
    due_date: d(2),
    status: "pending",
    order_index: 2,
    created_at: d(-2),
    updated_at: d(0),
  },
  {
    id: "ms-4",
    goal_id: "goal-resume-ui",
    workspace_id: "ws-ai-hackathon",
    title: "1. Core UI Components & Upload Flow",
    description: "Design dropzone, live upload progress, and report skeleton.",
    due_date: d(0),
    status: "completed",
    order_index: 0,
    created_at: d(-2),
    updated_at: d(0),
  },
  {
    id: "ms-5",
    goal_id: "goal-resume-ui",
    workspace_id: "ws-ai-hackathon",
    title: "2. Match Breakdown & Export",
    description: "Implement radar visualization, PDF download, and feedback box.",
    due_date: d(3),
    status: "in_progress",
    order_index: 1,
    created_at: d(-2),
    updated_at: d(0),
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-1",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-core",
    milestone_id: "ms-1",
    title: "Finalize AI Pipeline Architecture",
    description: "Document OpenAI embeddings vs Gemini API latency benchmarks and output structure.",
    priority: "high",
    status: "done",
    due_date: d(-1),
    estimated_hours: 4,
    created_by: "u-sushanth",
    assigned_to: "u-sushanth",
    order_index: 0,
    created_at: d(-2),
    updated_at: d(-1),
    subtasks: [
      { id: "st-1", task_id: "task-1", title: "Benchmark latency on 20 test resumes", is_completed: true, order_index: 0, created_at: d(-2) },
      { id: "st-2", task_id: "task-1", title: "Select vector chunking threshold (512 tokens)", is_completed: true, order_index: 1, created_at: d(-2) },
    ],
    tags: [{ id: "tag-ai", workspace_id: "ws-ai-hackathon", name: "AI/ML", color: "#8b5cf6" }],
  },
  {
    id: "task-2",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-core",
    milestone_id: "ms-2",
    title: "Train / Configure Extractor Model",
    description: "Extract candidate contact details, work history, skills array, and education accurately.",
    priority: "urgent",
    status: "in_progress",
    due_date: d(0), // Due today!
    estimated_hours: 6,
    created_by: "u-sushanth",
    assigned_to: "u-sushanth",
    order_index: 1,
    created_at: d(-1),
    updated_at: d(0),
    subtasks: [
      { id: "st-3", task_id: "task-2", title: "Write regex fallback for corrupted PDF text", is_completed: true, order_index: 0, created_at: d(-1) },
      { id: "st-4", task_id: "task-2", title: "Structure JSON output schema validation", is_completed: false, order_index: 1, created_at: d(-1) },
    ],
    tags: [{ id: "tag-ai", workspace_id: "ws-ai-hackathon", name: "AI/ML", color: "#8b5cf6" }],
  },
  {
    id: "task-3",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-ui",
    milestone_id: "ms-4",
    title: "Build Resume Drag & Drop Upload Page",
    description: "Smooth client-side PDF validation, page counter, and instant visual preview.",
    priority: "medium",
    status: "done",
    due_date: d(-1),
    estimated_hours: 5,
    created_by: "u-rahul",
    assigned_to: "u-rahul",
    order_index: 2,
    created_at: d(-2),
    updated_at: d(0),
    tags: [{ id: "tag-fe", workspace_id: "ws-ai-hackathon", name: "Frontend", color: "#3b82f6" }],
  },
  {
    id: "task-4",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-ui",
    milestone_id: "ms-5",
    title: "Design Radar Match Chart & Missing Skills Pill Box",
    description: "Visual breakdown comparing resume competencies with target job requirements.",
    priority: "high",
    status: "in_progress",
    due_date: d(1),
    estimated_hours: 4,
    created_by: "u-rahul",
    assigned_to: "u-rahul",
    order_index: 3,
    created_at: d(-1),
    updated_at: d(0),
    tags: [{ id: "tag-fe", workspace_id: "ws-ai-hackathon", name: "Frontend", color: "#3b82f6" }],
  },
  {
    id: "task-5",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-core",
    milestone_id: "ms-3",
    title: "Build Scoring & Vector Embedding API Route",
    description: "Compute cosine similarity between embedded JD requirements and candidate resume nodes.",
    priority: "urgent",
    status: "todo",
    due_date: d(1),
    estimated_hours: 6,
    created_by: "u-sushanth",
    assigned_to: "u-neha",
    order_index: 4,
    created_at: d(-1),
    updated_at: d(0),
    tags: [{ id: "tag-be", workspace_id: "ws-ai-hackathon", name: "Backend", color: "#10b981" }],
  },
  {
    id: "task-6",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-core",
    milestone_id: "ms-3",
    title: "Setup CI/CD Pipeline & Vercel Preview Deployments",
    description: "Automate build verification on pull request and verify environment secrets.",
    priority: "medium",
    status: "review",
    due_date: d(2),
    estimated_hours: 3,
    created_by: "u-sushanth",
    assigned_to: "u-priya",
    order_index: 5,
    created_at: d(-1),
    updated_at: d(0),
    tags: [{ id: "tag-devops", workspace_id: "ws-ai-hackathon", name: "DevOps", color: "#f59e0b" }],
  },
  {
    id: "task-7",
    workspace_id: "ws-ai-hackathon",
    goal_id: "goal-resume-core",
    milestone_id: "ms-3",
    title: "Draft Hackathon Demo Pitch & Slide Deck",
    description: "Prepare 3-minute pitch deck emphasizing the problem, market size, live demo, and architecture.",
    priority: "high",
    status: "backlog",
    due_date: d(3),
    estimated_hours: 4,
    created_by: "u-sushanth",
    assigned_to: "u-sushanth",
    order_index: 6,
    created_at: d(-1),
    updated_at: d(0),
    tags: [{ id: "tag-pitch", workspace_id: "ws-ai-hackathon", name: "Pitch", color: "#ec4899" }],
  },
  {
    id: "task-8",
    workspace_id: "ws-campus-portal",
    title: "Database Schema Migration for Student Records",
    description: "Implement PostgreSQL tables for semester course enrollments and GPA calculations.",
    priority: "urgent",
    status: "todo",
    due_date: d(-2), // Overdue!
    estimated_hours: 5,
    created_by: "u-rahul",
    assigned_to: "u-sushanth",
    order_index: 0,
    created_at: d(-5),
    updated_at: d(-2),
    tags: [{ id: "tag-be2", workspace_id: "ws-campus-portal", name: "Database", color: "#10b981" }],
  },
  {
    id: "task-9",
    workspace_id: "ws-ml-journey",
    title: "Complete PyTorch Multi-Head Attention from Scratch",
    description: "Implement scaled dot product attention and positional encodings in clean modular code.",
    priority: "high",
    status: "todo",
    due_date: d(4),
    estimated_hours: 8,
    created_by: "u-sushanth",
    assigned_to: "u-sushanth",
    order_index: 0,
    created_at: d(-3),
    updated_at: d(0),
    tags: [{ id: "tag-pytorch", workspace_id: "ws-ml-journey", name: "PyTorch", color: "#ea580c" }],
  }
];

export const INITIAL_COMMENTS = [
  {
    id: "com-1",
    task_id: "task-2",
    user_id: "u-rahul",
    content: "I cleaned the sample test dataset and pushed 30 PDF resumes to the test folder.",
    created_at: d(-0.2),
  },
  {
    id: "task-2-com-2",
    task_id: "task-2",
    user_id: "u-sushanth",
    content: "Great! I've hooked up the extractor and accuracy is at 94% on messy two-column layouts.",
    created_at: d(-0.1),
  },
  {
    id: "com-3",
    task_id: "task-6",
    user_id: "u-priya",
    content: "Preview deployments are active on Vercel. Every PR now gets an isolated database branch test.",
    created_at: d(-0.3),
  }
];

export const INITIAL_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-1",
    workspace_id: "ws-ai-hackathon",
    user_id: "u-sushanth",
    action_type: "task_completed",
    entity_type: "task",
    entity_id: "task-1",
    entity_title: "Finalize AI Pipeline Architecture",
    created_at: d(-0.05),
  },
  {
    id: "act-2",
    workspace_id: "ws-ai-hackathon",
    user_id: "u-rahul",
    action_type: "task_assigned",
    entity_type: "task",
    entity_id: "task-4",
    entity_title: "Design Radar Match Chart & Missing Skills Pill Box",
    created_at: d(-0.1),
  },
  {
    id: "act-3",
    workspace_id: "ws-ai-hackathon",
    user_id: "u-neha",
    action_type: "milestone_completed",
    entity_type: "milestone",
    entity_id: "ms-1",
    entity_title: "1. Problem & Architecture Spec",
    created_at: d(-0.5),
  },
  {
    id: "act-4",
    workspace_id: "ws-ai-hackathon",
    user_id: "u-priya",
    action_type: "status_changed",
    entity_type: "task",
    entity_id: "task-6",
    entity_title: "Setup CI/CD Pipeline & Vercel Preview Deployments",
    metadata: { from: "todo", to: "review" },
    created_at: d(-0.8),
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    user_id: "u-sushanth",
    workspace_id: "ws-ai-hackathon",
    title: "Task Assigned",
    message: "Rahul assigned you to 'Train / Configure Extractor Model'",
    type: "task_assigned",
    is_read: false,
    link_url: "/workspaces/ws-ai-hackathon/kanban",
    created_at: d(-0.05),
  },
  {
    id: "notif-2",
    user_id: "u-sushanth",
    workspace_id: "ws-campus-portal",
    title: "Task Overdue",
    message: "'Database Schema Migration for Student Records' is past due",
    type: "task_overdue",
    is_read: false,
    link_url: "/tasks",
    created_at: d(-0.2),
  },
  {
    id: "notif-3",
    user_id: "u-sushanth",
    workspace_id: "ws-ai-hackathon",
    title: "Milestone Completed",
    message: "Milestone '1. Problem & Architecture Spec' was completed by Neha",
    type: "milestone_completed",
    is_read: true,
    link_url: "/workspaces/ws-ai-hackathon/goals",
    created_at: d(-0.5),
  }
];
